
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 5;
  public static final int READ = 9;
  public static final int PLUS = 3;
  public static final int RPAREN = 11;
  public static final int GOTO = 13;
  public static final int SEMI = 2;
  public static final int GREATEROREQUALTHAN = 21;
  public static final int LESSOREQUALTHAN = 20;
  public static final int IF = 8;
  public static final int LPAREN = 10;
  public static final int COLON = 12;
  public static final int ID = 17;
  public static final int EQUALSEQUALS = 22;
  public static final int NOTEQUALS = 23;
  public static final int EQUALS = 6;
  public static final int STRING = 15;
  public static final int LESSTHAN = 19;
  public static final int EOF = 0;
  public static final int NUMBER = 16;
  public static final int MINUS = 4;
  public static final int PRINT = 7;
  public static final int error = 1;
  public static final int INTEGER = 14;
  public static final int GREATERTHAN = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "TIMES",
  "EQUALS",
  "PRINT",
  "IF",
  "READ",
  "LPAREN",
  "RPAREN",
  "COLON",
  "GOTO",
  "INTEGER",
  "STRING",
  "NUMBER",
  "ID",
  "GREATERTHAN",
  "LESSTHAN",
  "LESSOREQUALTHAN",
  "GREATEROREQUALTHAN",
  "EQUALSEQUALS",
  "NOTEQUALS"
  };
}

